# Generated by Django 4.2 on 2023-04-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_address_id_alter_cart_id_alter_department_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
